"""initial_tables

Revision ID: 6255554d5ddd
Revises: 
Create Date: 2026-01-04 14:38:21.088375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6255554d5ddd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###